# config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
  connections:
    default:
      server: "%mongodb_server%"
      options: {}
  default_database: veggies
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: attribute
          dir: '%kernel.project_dir%/src/Domain'
          prefix: 'App\Domain'
          alias: App
