services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx-fruits
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/
    networks:
      - app_network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fruits
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - app_network


networks:
  app_network:
