services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx-fruits
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/
    networks:
      - app_network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fruits
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    depends_on:
      - mongodb # Ensure MongoDB starts before the app
    environment:
      - MONGO_HOST=mongodb # Environment variable for MongoDB host
      - MONGO_PORT=27017 # Environment variable for MongoDB port

  mongodb:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
